name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          key: loco-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          path: |
            ~/builds
            ~/build
            ~/.gradle
            ~/.m2
      - name: Download, Compile and Install Paper
        run:  ./paper-nms.sh
      - name: Build with Gradle
        run: ./gradlew assemble
